site_name: JARVICE
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.path
    - toc.integrate
    - toc.follow
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
plugins:
    - search
    # - with-pdf:
    #     author: Nimbix
    #     copyright: '@2021 Nimbix'
    #     cover: true
    #     back_cover: false
    #     cover_title: Jarvice
    #     cover_subtitle: documentation
    #     toc_level: 2
    #     output_path: pdf/jarvice.pdf
extra_css:
    - css/extra.css
nav:
    - Home: index.md
    - PushToCompute: cicd.md
    - Docker Images on JARVICE: docker.md
    - Nimbix Application Environment: nae.md
    - MPI Application Configuration Guide: mpi.md
    - Application Definition Guide: appdef.md
    - The JARVICE API: api.md
    - Resource Selection: machines.md
    - JARVICE job recipe: recipe.md
    - Public Applications: public.md
    - Applications Tutorial: apps_tutorial.md
